function [D, X] = dictionary_learning(U, D_prev, max_iter, tol)
    %DICTIONARY LEARNING global implementation of DL
    %   
    %   param U (matrix): Matrix generated by ascii_to_data_matrix()
    % 
    %   param D_prev (matrix): Previous version of dictionary
    % 
    %   param max_iter (int): Maximum no. of iterations 
    %   
    %   param tol (float): tolerance for Frobenius norm convergence of D
    % 
    %   Perform dictionary learning, alternating between LASSO 
    %   for sparse coding and block coordinate descent for regression.
    %
    
    Udim = size(U);
    m = Udim(1);
    k = Udim(2);
    
    D = zeros(m, k);
    
    
    
    
    
    
end

