function D = init_dict(U, CODE_LEN)
    %   INIT_DICT help function to initialize dictionary from data U
    %   
    %   param U (matrix): matrix of data generated by
    %                       ascii_to_data_matrix()
    %
    %   param CODE_LEN (int): length of sparse code vectors. This will be
    %                           no. of cols in dictionary matrix.
    %   
    %   Randomly sample columns of U to be columns of D
    %
    %   Return D (matrix): Initial dictionary matrix with same no. of rows 
    %                        as U. No. of columns equal to CODE_LEN.
    
    
    rng(10, 'twister');
    s = RandStream('mlfg6331_64');
    
    %sample CODE_LEN columns with replacement 
    D = datasample(s, U, CODE_LEN, 2, 'replace', true); 
end

