function D = init_dict(U, CODE_LEN, normal)
    %   INIT_DICT help function to initialize dictionary from data U
    %   
    %   param U (matrix): matrix of data generated by
    %                       ascii_to_data_matrix()
    %
    %   param CODE_LEN (int): length of sparse code vectors. This will be
    %                           no. of cols in dictionary matrix.
    %   
    %   param normal (boolean): If true, initialization is generated with
    %   normal distribution. Otherwise, sample columns from U.
    %
    %   Return D (matrix): Initial dictionary matrix with same no. of rows 
    %                        as U. No. of columns equal to CODE_LEN.
    
    
    rng(42, 'twister');
    s = RandStream('mlfg6331_64');
    if normal
        sigma = std(U(:));
        mu = mean(U(:));
        nrows = length(U(:,1));
        D = normrnd(mu, sigma, nrows, CODE_LEN);
    else 
        % sample CODE_LEN columns with replacement 
        D = datasample(s, U, CODE_LEN, 2, 'replace', true); 
    end
    D = normc(D); % normalize columns
end

